eureka:
  server:
    enableSelfPreservation: false

---
spring:
  profiles: peer1
  application:
    name: eureka-server1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


---
spring:
  profiles: peer2
  application:
    name: eureka-server2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/