spring:
  application:
    name: service1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

---
spring:
  profiles: inst1
server:
  port: 8001


---
spring:
  profiles: inst2
server:
  port: 8002

