spring:
  application:
    name: feign-hystrix-consumer
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true # feign 中集成了 Hystrix，但是需要设置该值才能生效